# Generated by Django 3.1.3 on 2020-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
