# Generated by Django 3.1.3 on 2020-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0006_auto_20201207_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreview',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='autoreview',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='autoreview',
            name='titre',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='autoreview',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
