# Generated by Django 3.1.3 on 2020-12-11 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0007_auto_20201209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followed',
            field=models.ManyToManyField(blank=True, default=None, related_name='_customuser_followed_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Suivi', 'Suivi'), ('Suivre', 'Suivre')], default='UserFollow', max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
