# Generated by Django 3.1.3 on 2020-12-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0008_auto_20201211_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_created']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date',
            new_name='time_created',
        ),
    ]
