# Generated by Django 3.1.3 on 2020-12-15 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0009_auto_20201211_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='value',
        ),
        migrations.AddField(
            model_name='userfollow',
            name='followed_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='mvplit.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
