# Generated by Django 3.1.3 on 2020-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0011_customuser_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='value',
            field=models.CharField(choices=[('Suivi', 'Suivi'), ('Suivre', 'Suivre')], default='UserFollow', max_length=10),
        ),
    ]
