# Generated by Django 3.1.3 on 2020-12-17 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0012_userfollow_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_follower',
            field=models.ManyToManyField(blank=True, default=None, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
