# Generated by Django 3.1.3 on 2020-12-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvplit', '0013_auto_20201217_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_follower',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
